<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="4" total="6" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Name of the method executing is:test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context]]>
    </line>
    <line>
      <![CDATA[Step 1. Login to the DNAM Client..]]>
    </line>
    <line>
      <![CDATA[Step 2. Verify if the node is found....]]>
    </line>
    <line>
      <![CDATA[Name of the method executing is:test02_VerifyInventoryManagerExportForOCM8P_NE_Context]]>
    </line>
    <line>
      <![CDATA[Step 1. Login to the DNAM Client..]]>
    </line>
    <line>
      <![CDATA[Step 2. Verify if the node is found....]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="62255" started-at="2018-05-17T11:17:04Z" finished-at="2018-05-17T11:18:07Z">
    <groups>
      <group name="Inventory">
        <method signature="InventoryTests.test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context()[pri:0, instance:test.java.com.infinera.dnam.gui.inventory.InventoryTests@1a8a8f7c]" name="test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context" class="test.java.com.infinera.dnam.gui.inventory.InventoryTests"/>
        <method signature="InventoryTests.test02_VerifyInventoryManagerExportForOCM8P_NE_Context()[pri:0, instance:test.java.com.infinera.dnam.gui.inventory.InventoryTests@1a8a8f7c]" name="test02_VerifyInventoryManagerExportForOCM8P_NE_Context" class="test.java.com.infinera.dnam.gui.inventory.InventoryTests"/>
      </group> <!-- Inventory -->
    </groups>
    <test name="Default test" duration-ms="62255" started-at="2018-05-17T11:17:04Z" finished-at="2018-05-17T11:18:07Z">
      <class name="test.java.com.infinera.dnam.gui.inventory.InventoryTests">
        <test-method status="FAIL" signature="test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context()[pri:0, instance:test.java.com.infinera.dnam.gui.inventory.InventoryTests@1a8a8f7c]" name="test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context" duration-ms="31163" started-at="2018-05-17T11:17:04Z" description=" Verify the Inventory Manager and Filters for OCM8P from NE Context.." finished-at="2018-05-17T11:17:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Find_String.png on the screen.
  Line 1574, in file Region.java
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Find_String.png on the screen.
  Line 1574, in file Region.java

at test.java.com.infinera.dnam.gui.inventory.InventoryTests.test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context(InventoryTests.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Find_String.png on the screen.
  Line 1574, in file Region.java

at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
at org.sikuli.script.Region.wait(Region.java:1682)
at org.sikuli.script.Region.find(Region.java:1590)
at test.java.com.infinera.dnam.gui.inventory.InventoryTests.test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context(InventoryTests.java:72)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Name of the method executing is:test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context]]>
            </line>
            <line>
              <![CDATA[Step 1. Login to the DNAM Client..]]>
            </line>
            <line>
              <![CDATA[Step 2. Verify if the node is found....]]>
            </line>
          </reporter-output>
        </test-method> <!-- test01_VerifyInventoryManagerAndFiltersForOCM8P_NE_Context -->
        <test-method status="FAIL" signature="test02_VerifyInventoryManagerExportForOCM8P_NE_Context()[pri:0, instance:test.java.com.infinera.dnam.gui.inventory.InventoryTests@1a8a8f7c]" name="test02_VerifyInventoryManagerExportForOCM8P_NE_Context" duration-ms="31068" started-at="2018-05-17T11:17:35Z" finished-at="2018-05-17T11:18:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\nodeIp_10_210_130_171_Name.png on the screen.
  Line 1574, in file Region.java
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\nodeIp_10_210_130_171_Name.png on the screen.
  Line 1574, in file Region.java

at test.java.com.infinera.dnam.gui.inventory.InventoryTests.test02_VerifyInventoryManagerExportForOCM8P_NE_Context(InventoryTests.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\nodeIp_10_210_130_171_Name.png on the screen.
  Line 1574, in file Region.java

at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
at org.sikuli.script.Region.wait(Region.java:1682)
at org.sikuli.script.Region.find(Region.java:1590)
at test.java.com.infinera.dnam.gui.inventory.InventoryTests.test02_VerifyInventoryManagerExportForOCM8P_NE_Context(InventoryTests.java:240)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Name of the method executing is:test02_VerifyInventoryManagerExportForOCM8P_NE_Context]]>
            </line>
            <line>
              <![CDATA[Step 1. Login to the DNAM Client..]]>
            </line>
            <line>
              <![CDATA[Step 2. Verify if the node is found....]]>
            </line>
          </reporter-output>
        </test-method> <!-- test02_VerifyInventoryManagerExportForOCM8P_NE_Context -->
      </class> <!-- test.java.com.infinera.dnam.gui.inventory.InventoryTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
