<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Step 1. Login to the DNAM Client..]]>
    </line>
    <line>
      <![CDATA[Step 2. Verify is the node is found....]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="32461" started-at="2018-05-14T06:15:30Z" finished-at="2018-05-14T06:16:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32461" started-at="2018-05-14T06:15:30Z" finished-at="2018-05-14T06:16:03Z">
      <class name="com.infinera.dnam.gui.events.EventsTests">
        <test-method status="FAIL" signature="test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context()[pri:0, instance:com.infinera.dnam.gui.events.EventsTests@366e2eef]" name="test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context" duration-ms="32436" started-at="2018-05-14T06:15:30Z" finished-at="2018-05-14T06:16:03Z">
          <exception class="org.sikuli.script.FindFailed">
            <message>
              <![CDATA[can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Subnet1_sawan.png on the screen.]]>
            </message>
            <full-stacktrace>
              <![CDATA[FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Subnet1_sawan.png on the screen.
  Line 1574, in file Region.java

at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
at org.sikuli.script.Region.wait(Region.java:1682)
at org.sikuli.script.Region.find(Region.java:1590)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:1991)
at org.sikuli.script.Region.click(Region.java:2197)
at org.sikuli.script.Region.click(Region.java:2181)
at com.infinera.dnam.gui.events.EventsTests.test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context(EventsTests.java:426)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.sikuli.script.FindFailed -->
          <reporter-output>
            <line>
              <![CDATA[Step 1. Login to the DNAM Client..]]>
            </line>
            <line>
              <![CDATA[Step 2. Verify is the node is found....]]>
            </line>
          </reporter-output>
        </test-method> <!-- test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context -->
      </class> <!-- com.infinera.dnam.gui.events.EventsTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
