<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IN-SDakinedi-LT" name="com.infinera.dnam.gui.events.EventsTests" tests="4" failures="0" timestamp="14 May 2018 06:16:03 GMT" time="32.436" errors="1">
  <testcase name="test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context" time="32.436" classname="com.infinera.dnam.gui.events.EventsTests">
    <error type="org.sikuli.script.FindFailed" message="can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Subnet1_sawan.png on the screen.">
      <![CDATA[FindFailed: can not find C:\Users\sdakinedi\Desktop\JAVA\Eclipse_workspace\dnamGuiTesting_Java\lib\Subnet1_sawan.png on the screen.
  Line 1574, in file Region.java

at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
at org.sikuli.script.Region.wait(Region.java:1682)
at org.sikuli.script.Region.find(Region.java:1590)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:1991)
at org.sikuli.script.Region.click(Region.java:2197)
at org.sikuli.script.Region.click(Region.java:2181)
at com.infinera.dnam.gui.events.EventsTests.test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context(EventsTests.java:426)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test16_Verify_ExportOfEvents_ForOCM8P_Subnet_Context -->
  <testcase name="test21_Verify_EventsReportingAndFilters_ForOCM8P_Network_Context" classname="com.infinera.dnam.gui.events.EventsTests">
    <skipped/>
  </testcase> <!-- test21_Verify_EventsReportingAndFilters_ForOCM8P_Network_Context -->
  <testcase name="test15_Verify_EventsReportingAndFilters_ForOCM8P_Subnet_Context" classname="com.infinera.dnam.gui.events.EventsTests">
    <skipped/>
  </testcase> <!-- test15_Verify_EventsReportingAndFilters_ForOCM8P_Subnet_Context -->
  <testcase name="test22_Verify_ExportOfEvents_ForOCM8P_Network_Context" classname="com.infinera.dnam.gui.events.EventsTests">
    <skipped/>
  </testcase> <!-- test22_Verify_ExportOfEvents_ForOCM8P_Network_Context -->
</testsuite> <!-- com.infinera.dnam.gui.events.EventsTests -->
